run: "test-mof-001"

global_seed: 22463

# setup for neighbors
nbrs:
    buff_type: 'tot'
    buff_frac: 0.25
    maxsize_to_replace: 256
    new_maxsize: 384
    check_seg: True


# job setup
jobs:
    # for MOF this refers to the number of FOFs in a chunk,
    # otherwise it is the number of objects
    chunksize: 100

    # what to do
    bands: ['g','r','i','z']

collate:
    # how to combine results
    concat_type: 'concat-des'



fitter_type: "max-ngmix-boot"
imageio_type: "meds-des-y3"

fit_me_galaxy: True
fit_coadd_galaxy: False

read_wcs: False
read_me_wcs: False


# mof stuff
model_nbrs: True
model_nbrs_method: 'subtract'
mof:
    maxabs_conv:  [1.0e-3,1.0e-3,1.0e-6,1.0e-6,1.0e-6,1.0e-6,1.0e-6,1.0e-6,1.0e-6]
    maxfrac_conv: [1.0e-6,1.0e-6,1.0e-6,1.0e-6,1.0e-6,1.0e-3,1.0e-3,1.0e-3,1.0e-3]
    maxerr_conv: 0.5 
    max_itr: 15
    min_itr: 10
    min_useg_itr: 1
    write_convergence_data: False
    convergence_model: 'cm'


prop_sat_starpix: True
flag_y1_stellarhalo_masked: True
intr_prof_var_fac: 0.0


max_pars:
    method: 'lm'
    ntry: 2

    use_fracdev_grid: False
    fracdev_range: [0.0,1.0]
    TdByTe_range: [0.0,1.0e+12]
    
    lm_pars:
        maxfev: 2000
        xtol: 5.0e-5
        ftol: 5.0e-5

reject_outliers: True

make_corrected_meds: False

# we try to do most stuff for mof
max_bmask_frac: 0.1
max_zero_weight_frac: 0.1

# don't need this since we are rejecting anything witha bad pixel
replace_bad_pixels: False

# no need for this, since we don't allow any bits set in mask
symmetrize_bmask: False

# not sure if we should do this one
symmetrize_weight: False

# skip when either all weight or all image are zero
ignore_zero_weights_images: True


# skip if central region is masked
# this is a 4 pixel offset in each direction
central_bmask_radius: 4

#max_box_size: 48

region: "mof"

min_weight: 0.0

# flagging
#replacement_flags: "${DESDATA}/EXTRA/combined-image-flags/sva1_astrom_run1.0.1_stats_flagged_sheldon_psfv3_blacklists.json"

# astrom
# 2**0 + 2**1 + 2**2 + 2**3 + 2**5 + 2**6 + 2**7 + 2**8 + 2**9
#  = 1007
# blacklists
# 2**(10+0) + 2**(10+1) + 2**(10+2) + 2**(10+3) + 2**(10+4) = (31<<10)
#  = 31744
# psf
# 2**(15+0) + 2**(15+1) + 2**(15+4)
#  = (19<<15)
# total
# 
# 1007 + (31<<10) + (19<<15)
#  = 655343

image_flags2check: 655343

use_psf_rerun: False
normalize_psf: False
center_psf: False

print_params: True

psf_pars:
    model: 'em3'
    ntry: 20
    fit_pars:
      maxiter: 5000
      tol: 5.0e-6

replace_cov: False
cov_pars:
    m: 5
    h: 1.0e-3

round_pars:
    fitter_type: 'max'

use_logpars: False
model_pars:
    cm:
        g:
            type: "cosmos-sersic"

        T:
            type: "TwoSidedErf"
            pars: [-10.0, 0.03, 1.0e+06, 1.0e+05]

        counts:
            type: "TwoSidedErf"
            pars: [-1.0e+04, 1.0, 1.0e+09, 0.25e+08]
            repeat: True

        cen:
            type: "dgauss"
            width: 0.27

        # for now use stuff from great-des
        fracdev:
            file: "$DESDATA/EXTRA/aux/priors/sfit-noisefree-c01-fracdev.fits"

do_shear: False

# checkpoint times in minutes, needed for condor in case we pass a batch system
# limit such as in the condor scavenge.
# 0 means after the first object

# checkpoints for lsf
checkpoints: [0,5,10,15,20,25,
              30,60,
              90,120, 
              150,180,
              210,240,
              270,300,
              330,360,
              390,420,
              480,540,
              600,700,
              800,900,1000,1200,1400,1600,1800,2000]
