run: "testdeep-mof-001"

global_seed: 7412

# job setup
jobs:
    # for MOF this refers to the number of FOFs in a chunk,
    # otherwise it is the number of objects
    chunksize: 100

    # what to do
    bands: ['g','r','i','z']

collate:
    # how to combine results
    concat_type: 'concat-des'
    blinding: null


fitter_type: "max-ngmix-boot"
imageio:
    io_type: "meds-des-y3"
    image_type: "flux"

    psfs:
        type: "psfex"


fit_me_galaxy: False
fit_coadd_galaxy: True
use_coadd_prefix: False

read_wcs: False
read_me_wcs: False

# setup for neighbors
nbrs:
    buff_type: 'tot'
    buff_frac: 0.25
    maxsize_to_replace: 256
    new_maxsize: 384
    check_seg: True


# mof stuff
model_nbrs: True
model_nbrs_method: 'subtract'
mof:
    maxabs_conv:  [1.0e-3,1.0e-3,1.0e-6,1.0e-6,1.0e-6,1.0e-6,1.0e-6,1.0e-6,1.0e-6]
    maxfrac_conv: [1.0e-6,1.0e-6,1.0e-6,1.0e-6,1.0e-6,1.0e-3,1.0e-3,1.0e-3,1.0e-3]
    maxerr_conv: 0.5 
    max_itr: 15
    min_itr: 10
    min_useg_itr: 1
    write_convergence_data: False
    convergence_model: 'cm'


propagate_star_flags:
    # propagate SATURATE, INTERP between
    # bands and epochs
    propagate: True

    # don't propagate if these bits are also set for
    # the same pixel
    ignore_when_set: [
        SUSPECT,
        SSXTALK,
        EDGEBLEED,
        CRAY,
        BADAMP,
        BPM,
    ]

# throw out postage stamps for which the seg map of the
# central object intersects a bright star mask
flag_y1_stellarhalo_masked: False

# if > 0, will add in estimate for intrinsic profile variance 
intr_prof_var_fac: 0.0

reject_outliers: True

# the input images have zero weight when lots of bits are set
# Setting these will zero out more
extra_mask_flag_list: [
    SATURATE,
    INTERP,
    #NEAREDGE, #doesn't exist in Y3
    #TAPEBUMP, #doesn't exist in Y3
    SUSPECT, # subsumes some others, including NEAREDGE,TAPEBUMP
]


make_corrected_meds: False

# we try to do most stuff for mof
max_zero_weight_frac: 0.45

# don't need this since we have set weight for these
replace_bad_pixels: False

# no need for this for max likelihood
symmetrize_weight: False

# skip when either all weight or all image are zero
ignore_zero_weights_images: True

# uberseg + mof specifics
region: "mof"

# we don't  have any image flags yet for Y3
image_flags2check: 655343

normalize_psf: True

print_params: True

max_pars:
    method: 'lm'
    ntry: 2

    use_fracdev_grid: False
    fracdev_range: [0.0,1.0]
    TdByTe_range: [0.0,1.0e+12]
    
    lm_pars:
        maxfev: 2000
        xtol: 5.0e-5
        ftol: 5.0e-5

psf_pars:
    model: 'em3'
    ntry: 20
    fit_pars:
      maxiter: 5000
      tol: 5.0e-6

replace_cov: False
cov_pars:
    m: 5
    h: 1.0e-3

round_pars:
    fitter_type: 'max'

use_logpars: False
model_pars:
    cm:
        g:
            type: "cosmos-sersic"

        T:
            type: "TwoSidedErf"
            pars: [-10.0, 0.03, 1.0e+06, 1.0e+05]

        counts:
            type: "TwoSidedErf"
            pars: [-1.0e+04, 1.0, 1.0e+09, 0.25e+08]
            repeat: True

        cen:
            type: "dgauss"
            width: 0.27

        # for now use stuff from great-des
        fracdev:
            weights: [ 0.07219169,  0.03931063,  0.06144639,  0.02342249,  0.05680965,
                       0.07317471,  0.07112629,  0.05102051,  0.03397887,  0.06657475,
                       0.02908218,  0.01747496,  0.06998605,  0.00772567,  0.02882283,
                       0.04503099,  0.06212688,  0.06761242,  0.0502267 ,  0.07285532]
            means: [-0.0621139 ,  0.48460298, -0.16349622,  0.81232456,  0.1555424 ,
                     -0.08928717, -0.12935131,  0.25287222,  0.5998589 ,  0.01771045,
                     -0.21265698,  0.90599701, -0.02775166,  1.03471975,  0.7096433 ,
                     0.36650008,  0.07729925, -0.14636961, -0.18364023, -0.11087039]
            covars: [ 0.05039464,  0.14833301,  0.02533687,  0.08991854,  0.11303651,
                      0.04256832,  0.03219367,  0.13369827,  0.13584953,  0.07452398,
                      0.02094517,  0.0701313 ,  0.06071257,  0.05520489,  0.11392525,
                      0.14748899,  0.09209303,  0.02847802,  0.02259679,  0.03674909]

do_shear: False

# checkpoint times in minutes, needed for condor in case we pass a batch system
# limit such as in the condor scavenge.
# 0 means after the first object

# checkpoints for lsf
checkpoints: [0,5,10,15,20,25,
              30,60,
              90,120, 
              150,180,
              210,240,
              270,300,
              330,360,
              390,420,
              480,540,
              600,700,
              800,900,1000,1200,1400,1600,1800,2000]
